from pathlib import Path

p = Path("tests/ccos-enterprise-conformance/tests/stress_budget_property.rs")
s = p.read_text()
old = '''/// The allowlist accepts entries the gateway would refuse outright for a tool:\n/// the empty string, whitespace, control bytes. Nothing canonicalizes an\n/// allowlist entry on the way in, so `allow_model("")` really does make the\n/// empty model name a governed, billable model.\n///\n/// Not a hole by itself — you have to configure it — but it is the mirror of\n/// the gateway's canonicality check, which exists precisely because "the\n/// boundary never forwards what it cannot classify".\n#[test]\nfn the_allowlist_accepts_non_canonical_entries() {\n    let mut d = Deployment::new();\n    d.add_role("writer", &["memory.write"])\n        .govern_tool("memory.ingest", "memory.write");\n    let mut t = TenantState::new(100);\n    t.allow_model("").allow_model(" ").allow_model("a\\nb");\n    assert!(d.add_tenant("o", "acme", t));\n    assert!(d.assign("a", "writer"));\n    let who = actor("o", "a", AuthStrength::Token);\n\n    for (i, model) in ["", " ", "a\\nb"].into_iter().enumerate() {\n        let req = request("acme", "a", "memory.ingest", &format!("r-{i}"));\n        assert_eq!(\n            d.admit(Call {\n                actor: &who,\n                request: &req,\n                model,\n                cost_tokens: 1,\n                variant: None,\n                justification: None,\n            }),\n            Outcome::Forwarded,\n            "TRUTH: {model:?} is a perfectly good model name to the allowlist"\n        );\n    }\n    assert_eq!(d.spent("acme"), Some(3), "and all three calls were billed");\n\n    // The gateway refuses exactly these spellings for a tool name.\n'''
new = '''/// The allowlist accepts entries the gateway would refuse outright for a tool:\n/// the empty string, whitespace, control bytes. Nothing canonicalizes an\n/// allowlist entry on the way in. Selection is now a separate invariant: only\n/// the explicitly active model may execute even when several raw entries are\n/// stored in the allowlist.\n///\n/// Not a hole by itself — you have to configure it — but it is the mirror of\n/// the gateway's canonicality check, which exists precisely because "the\n/// boundary never forwards what it cannot classify".\n#[test]\nfn the_allowlist_accepts_non_canonical_entries() {\n    let mut d = Deployment::new();\n    d.add_role("writer", &["memory.write"])\n        .govern_tool("memory.ingest", "memory.write");\n    let mut t = TenantState::new(100);\n    t.allow_model("").allow_model(" ").allow_model("a\\nb");\n    assert!(d.add_tenant("o", "acme", t));\n    assert!(d.assign("a", "writer"));\n    let who = actor("o", "a", AuthStrength::Token);\n\n    let stored = d.tenant_models("acme").expect("tenant model allowlist");\n    assert_eq!(stored.len(), 3);\n    for model in ["", " ", "a\\nb"] {\n        assert!(\n            stored.contains(model),\n            "TRUTH: raw non-canonical entry {model:?} is still stored in the allowlist"\n        );\n    }\n\n    // The first configured entry is the initial explicit selection. The two\n    // other allowlisted spellings cannot execute until a governed switch\n    // selects them.\n    assert_eq!(\n        d.tenant_active_model(&ccos_enterprise_tenancy::TenantId("acme".into()))\n            .as_deref(),\n        Some("")\n    );\n    for (i, model) in ["", " ", "a\\nb"].into_iter().enumerate() {\n        let req = request("acme", "a", "memory.ingest", &format!("r-{i}"));\n        let outcome = d.admit(Call {\n            actor: &who,\n            request: &req,\n            model,\n            cost_tokens: 1,\n            variant: None,\n            justification: None,\n        });\n        if model.is_empty() {\n            assert_eq!(outcome, Outcome::Forwarded);\n        } else {\n            assert_eq!(outcome.refusal(), Some(&Refusal::ModelNotAllowed));\n        }\n    }\n    assert_eq!(\n        d.spent("acme"),\n        Some(1),\n        "only the selected non-canonical model is billable"\n    );\n\n    // The gateway refuses exactly these spellings for a tool name.\n'''
if s.count(old) != 1:
    raise SystemExit(f"stress allowlist anchor count: {s.count(old)}")
p.write_text(s.replace(old, new, 1))
