[package]
name = "ccos-enterprise-octasoma"
version = "0.1.0-pre"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
ccos-enterprise-memory = { path = "../ccos-enterprise-memory" }
ccos-enterprise-tenancy = { path = "../ccos-enterprise-tenancy" }
octasoma.workspace = true