#!/usr/bin/env bash
# check-author-policy.sh — enforce the single-human-contributor policy (§13, §43).
#
# The repository has one authorized human contributor, who may legitimately
# appear under more than one Git author/committer display name depending on the
# tool used to create a commit. Those aliases are normalized to one logical
# human identity before the policy is evaluated.
#
# Authorized aliases for the same human contributor:
#   - ZEKRITI Tarek
#   - MEMOPERF
#
# What is forbidden:
#   - any author/committer identity that does not normalize to the authorized
#     human contributor;
#   - AI or bot identities (Claude, Codex, ChatGPT, Copilot, Gemini, Kimi, …);
#   - contribution trailers (Co-authored-by, Generated-by, …);
#   - AI-attribution phrases ("generated by/with …", "AI-generated", session trailers).
#
# What is ALLOWED: technical references to model providers (Anthropic, OpenAI,
# Ollama, …) — the project ships provider adapters (mission §30). Attribution
# is forbidden, interoperability is not.
#
# MERGE COMMITS are exempt from the IDENTITY rules only. GitHub's "Merge pull
# request" button stamps the clicking account as author and
# `GitHub <noreply@github.com>` as committer — identities no contributor can
# set — so enforcing them there makes the policy unsatisfiable for any merge
# performed through the web UI, and permanently reddens main. A merge commit
# also carries no content of its own: every commit it merges is checked on its
# own line, so nothing escapes review. Their MESSAGE is still scanned, which is
# what matters — a merge message is hand-editable, and a squash merge can carry
# a whole pull-request body.
#
# WEB-UI SQUASHES get the same narrow identity exemption, for the same reason:
# the button writes `GitHub <noreply@github.com>` as committer no matter how
# the contributor merged, so demanding a normalized committer there is equally
# unsatisfiable-after-the-fact and permanently reddens main. The bar stays
# high where it means something: the AUTHOR must normalize to the authorized
# human, the committer must be *exactly* GitHub's noreply stamp (not merely a
# name someone could type), and every message rule still applies.
#
# Squash merges made LOCALLY are not exempt (both identities are under the
# contributor's control): they must carry the human identity on both sides,
# exactly like any ordinary commit.
#
# Usage:
#   scripts/check-author-policy.sh           # check HEAD commit
#   scripts/check-author-policy.sh A..B      # check a commit range
set -euo pipefail
cd "$(dirname "$0")/.."

RANGE="${1:-HEAD}"
CANONICAL_HUMAN_ID="zekriti-tarek"
# The committer stamp GitHub's web UI writes and no contributor can set. It
# is accepted only when the author already normalized to the human above.
WEB_STAMP_CN="GitHub"
WEB_STAMP_CE="noreply@github.com"

# Map every verified display-name alias for the same authorized human to one
# stable logical ID. New aliases must be added explicitly here; unknown names
# continue to fail closed.
canonical_human_id() {
  case "$1" in
    "ZEKRITI Tarek"|"MEMOPERF")
      printf '%s\n' "$CANONICAL_HUMAN_ID"
      ;;
    *)
      return 1
      ;;
  esac
}

IDENTITY_RE='claude|anthropic|chatgpt|codex|copilot|gemini|kimi|opencode|\bbot\b|noreply@anthropic'
TRAILER_RE='^(co-?authored-by|co-developed-by|contributed-by|generated-by|assisted-by|suggested-by|[a-z-]*-session)\s*:'
ATTRIBUTION_RE='generated (by|with) (claude|chatgpt|codex|copilot|gemini|kimi|opencode|ai)|ai[- ]generated|ai[- ]assisted|written by (claude|chatgpt|codex|kimi|ai)'

fail=0
while IFS=$'\t' read -r h an ae cn ce parents; do
  # More than one parent = a merge commit (see the header): identity exempt,
  # message still enforced.
  case "$parents" in
    *' '*) is_merge=1 ;;
    *) is_merge=0 ;;
  esac
  if [ "$is_merge" -eq 0 ]; then
    author_id="$(canonical_human_id "$an" 2>/dev/null || true)"
    if [ "$author_id" != "$CANONICAL_HUMAN_ID" ]; then
      echo "::error::$h author is '$an'; it does not normalize to the authorized human identity"
      fail=1
    elif [ "$cn" = "$WEB_STAMP_CN" ] && [ "$ce" = "$WEB_STAMP_CE" ]; then
      : # web-UI squash stamp: the author is proved, the committer is GitHub's own
    else
      committer_id="$(canonical_human_id "$cn" 2>/dev/null || true)"
      if [ "$committer_id" != "$CANONICAL_HUMAN_ID" ]; then
        echo "::error::$h committer is '$cn'; it does not normalize to the authorized human identity"
        fail=1
      fi
    fi
    if echo "$an$ae$cn$ce" | grep -Eiq "$IDENTITY_RE"; then
      echo "::error::$h AI/bot identity detected"
      fail=1
    fi
  fi
  message=$(git log -1 --format='%B' "$h")
  if echo "$message" | grep -Eiq "$TRAILER_RE"; then
    echo "::error::$h forbidden contribution trailer"
    fail=1
  fi
  if echo "$message" | grep -Eiq "$ATTRIBUTION_RE"; then
    echo "::error::$h AI attribution phrase in commit message"
    fail=1
  fi
done < <(git log --format='%H%x09%an%x09%ae%x09%cn%x09%ce%x09%P' "$RANGE")

if [ "$fail" -ne 0 ]; then
  echo "AUTHOR POLICY: FAILED"
  exit 1
fi
echo "AUTHOR POLICY: PASS ($RANGE)"
