#!/usr/bin/env bash
# check-author-policy.sh — enforce the single-human-contributor policy (§13, §43).
#
# What is forbidden:
#   - any author/committer identity other than ZEKRITI Tarek;
#   - AI or bot identities (Claude, Codex, ChatGPT, Copilot, Gemini, Kimi, …);
#   - contribution trailers (Co-authored-by, Generated-by, …);
#   - AI-attribution phrases ("generated by/with …", "AI-generated", session trailers).
#
# What is ALLOWED: technical references to model providers (Anthropic, OpenAI,
# Ollama, …) — the project ships provider adapters (mission §30). Attribution
# is forbidden, interoperability is not.
#
# MERGE COMMITS ARE SKIPPED. A pull request merged through GitHub's UI produces
# a merge commit authored by the account that clicked the button and committed
# by "GitHub" — an identity no contributor can influence and that can never
# equal EXPECTED_NAME. Checking them made the policy unsatisfiable: every merge
# to main turned CI red, e.g. the run for the merge of #1 failed with
#   cbb2243 author/committer is 'MEMOPERF'/'GitHub', expected 'ZEKRITI Tarek'
# while every commit it brought in was correctly authored. A merge commit
# carries no authored content of its own, so skipping it costs no coverage —
# the commits being merged are still each checked.
#
# Usage:
#   scripts/check-author-policy.sh           # check HEAD commit
#   scripts/check-author-policy.sh A..B      # check a commit range
set -euo pipefail
cd "$(dirname "$0")/.."

RANGE="${1:-HEAD}"
EXPECTED_NAME="ZEKRITI Tarek"

IDENTITY_RE='claude|anthropic|chatgpt|codex|copilot|gemini|kimi|opencode|\bbot\b|noreply@anthropic'
TRAILER_RE='^(co-?authored-by|co-developed-by|contributed-by|generated-by|assisted-by|suggested-by|[a-z-]*-session)\s*:'
ATTRIBUTION_RE='generated (by|with) (claude|chatgpt|codex|copilot|gemini|kimi|opencode|ai)|ai[- ]generated|ai[- ]assisted|written by (claude|chatgpt|codex|kimi|ai)'

fail=0
while IFS=$'\t' read -r h an ae cn ce; do
  if [ "$an" != "$EXPECTED_NAME" ] || [ "$cn" != "$EXPECTED_NAME" ]; then
    echo "::error::$h author/committer is '$an'/'$cn', expected '$EXPECTED_NAME'"
    fail=1
  fi
  if echo "$an$ae$cn$ce" | grep -Eiq "$IDENTITY_RE"; then
    echo "::error::$h AI/bot identity detected"
    fail=1
  fi
  if git log -1 --format='%B' "$h" | grep -Eiq "$TRAILER_RE"; then
    echo "::error::$h forbidden contribution trailer"
    fail=1
  fi
  if git log -1 --format='%B' "$h" | grep -Eiq "$ATTRIBUTION_RE"; then
    echo "::error::$h AI attribution phrase in commit message"
    fail=1
  fi
done < <(git log --no-merges --format='%H%x09%an%x09%ae%x09%cn%x09%ce' "$RANGE")

if [ "$fail" -ne 0 ]; then
  echo "AUTHOR POLICY: FAILED"
  exit 1
fi
echo "AUTHOR POLICY: PASS ($RANGE)"
